version: "3.8"
services:

  postgresql:
    image: postgres:13.7
    container_name: postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"
      - "POSTGRES_DB=keycloak"
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "81:80"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=admin@admin.com"
      - "PGADMIN_DEFAULT_PASSWORD=admin"

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.0
    environment:
      - "KC_DB=postgres"
      - "KC_DB_URL=jdbc:postgresql://postgresql:5432/keycloak"
      - "KC_DB_USERNAME=admin"
      - "KC_DB_PASSWORD=admin"
      - "KEYCLOAK_ADMIN=admin"
      - "KEYCLOAK_ADMIN_PASSWORD=admin"
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8081:8081
    command: [ "start-dev", "--http-port=8081" ]
    depends_on:
      - postgresql

volumes:
  db: